### PR TITLE
No need to build .png files out of .svg files.

### PR DESCRIPTION
**Pull request by yueyuzhao**
Considering there is no need to build .svg files to .png any more and this will make build this project easier.
Issue: #200 
I only have an Android v6.0 devices in hand, so this is not tested on v4.4.

### CODE REVIEW

**Comment by yueyuzhao** [comment]
OK, I tested this on a v4.4 virtual device, and all work fine. Cheers.

**Comment by chrisgarrity** [comment]
@yueyuzhao just to say again that these are all really helpful PRs. Unfortunately, with the work I need to get done for the Scratch 3.0 launch I'm not going to be able to review/build them for a while.  We really appreciate all your help.

**Comment by yueyuzhao** [comment]
OK, that's totally fine. Just take your time.
Great work for Scratch 3.0!
Come on!

**Comment by yueyuzhao** [comment]
Hi, changing png to svg may cause performance issues, so I decided to close this.

**Comment by chrisgarrity** [comment]
@yueyuzhao I was just testing it on a 5.1 device, and it wasn't bad. But I would need to try it on a 4.4 as it was rendering performance that required the png's in the first place.

**Comment by yueyuzhao** [comment]
Hi @chrisgarrity, thanks for your effort on this. If you had any test result, please let me know. Many thanks in advance.

**Comment by chrisgarrity** [comment]
@yueyuzhao this change would require more testing on more devices than we really have the resources to do. So it's too risky to put in.

**Comment by yueyuzhao** [comment]
agreed!

**Pull request closed without merging**
